### ISSUE TITLE
Feature Request: Push selection to bottom of another file

### ISSUE THREAD

**Issue by bturloff** [TfTHacker/obsidian42-text-transporter#61]
Have the option to push to the bottom of another file instead of the top.

**Comment by m0rtyn** [comment]
A really desired feature, I think about it every day.

**Comment by TfTHacker** [comment]
You can do this with a few other keyboard strokes. here is a video demonstrating how.
![Save to bottom of file](https://user-images.githubusercontent.com/69121180/220982029-6171b2f8-2612-4cee-be0a-f9125bc59452.gif)

**Comment by m0rtyn** [comment]
@TfTHacker thank you for the quick response.

I have found another way to solve my problem temporarily by creating a bookmark that allows me to move text to the bottom quickly. However, this is not a permanent solution, as I need to recreate a new bookmark every month.

Unfortunately, I cannot use your suggestion because it is not possible to move lines to the bottom of files longer than approximately 100 lines. This is because I am dealing with many buffers that are much longer than 100 lines in my use case.
